import proguard.gradle.ProGuardTask

buildscript {
    repositories { mavenCentral() }
    dependencies { classpath("com.guardsquare:proguard-gradle:7.9.1") }
}

plugins {
    application
}

group = "com.tonicbox.dukes8bit"
version = "1.0"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // The build-time passes merge Main into Game (see buildSrc dukes.build.merge), so Game is the entry point.
    mainClass = "Game"
}

tasks.withType<JavaCompile>().configureEach {
    options.release = 25
    options.isDebug = false
    options.encoding = "UTF-8"
}

// ProGuard minifies in place, so feeding already-minified classes back in would double-minify and drift the
// byte count. Clean-recompile each run to keep the minify input pristine and `size` deterministic.
tasks.named<JavaCompile>("compileJava") {
    outputs.upToDateWhen { false }
    doFirst { destinationDirectory.get().asFile.deleteRecursively() }
}

// The compiled-classes directory the bytecode passes transform and ProGuard later minifies in place.
val classesDir = layout.buildDirectory.dir("classes/java/main").get().asFile

// Runs the build-time bytecode passes (see buildSrc dukes.build.BuildPasses) over the freshly compiled classes,
// before the jar and ProGuard:
// - pack each class's constant Color fields into a decoded palette
// - Method Inlining. The inline list comes from inline-allowlist.txt (generated by tools/tune-inline.sh) or -Pinline=Game#a,Renderer#b for one-off experiments.
val allowlistFile = layout.projectDirectory.file("inline-allowlist.txt").asFile
val explicitInline: List<String>? = (findProperty("inline") as String?)
    ?.split(",")?.map { it.trim() }?.filter { it.isNotEmpty() }
val transformClasses = tasks.register("transformClasses") {
    dependsOn("compileJava")
    outputs.upToDateWhen { false }
    doLast {
        val allowlist = explicitInline ?: if (allowlistFile.exists())
            allowlistFile.readLines().map { it.trim() }.filter { it.isNotEmpty() && !it.startsWith("//") }
        else emptyList()
        dukes.build.BuildPasses.apply(classesDir, allowlist)
    }
}

// Lists every private single-call candidate (on the freshly compiled, pre-transform classes) for the tuner.
tasks.register("listInlineCandidates") {
    dependsOn("compileJava")
    doLast {
        dukes.build.inline.MethodInliner.discoverCandidates(classesDir).sorted().forEach { println(it) }
    }
}

// No runtime deps, so the plain jar is already runnable. Force a repackage each run so ProGuard minifies
// freshly-compiled classes rather than re-minifying a previous jar.
tasks.jar {
    archiveBaseName = "DukesDescent"
    manifest { attributes["Main-Class"] = "Game" }
    dependsOn(transformClasses)
    outputs.upToDateWhen { false }
}

tasks.register<ProGuardTask>("proguard") {
    group = "build"
    description = "Minify in place (shrink + shorten members, keep class names): the jar and compiled classes."
    dependsOn("jar")
    // Always re-run: it overwrites the compile/jar outputs, which would confuse up-to-date checks.
    outputs.upToDateWhen { false }

    val jdk = System.getProperty("java.home")
    val jarFile = layout.buildDirectory.file("libs/DukesDescent-$version.jar").get().asFile
    val tmpJar = layout.buildDirectory.file("tmp/proguard-min.jar").get().asFile

    injars(jarFile)
    outjars(tmpJar)
    libraryjars("$jdk/jmods/java.base.jmod")
    libraryjars("$jdk/jmods/java.desktop.jmod")

    // Keep the launch entry point; shrinking may still drop anything unused. Main is merged into Game by the
    // build-time passes, so Game (made public by the merge) carries main().
    keep("public class Game { public static void main(java.lang.String[]); static void main(); }")

    // Keep class names readable; members may shorten. Two optimizations are off because they grow this build:
    // unique-method inlining (cascades the program into Main, ~+13 KB) and parameter propagation (~+17 B).
    // 8 passes is where the optimizer converges.
    keepnames("class **")
    overloadaggressively()
    allowaccessmodification()
    optimizationpasses(8)
    optimizations("!class/merging/*,!method/inlining/unique,!method/propagation/*")
    dontwarn()
    dontnote()

    doLast {
        // Swap in the minified jar, then replace the compiled classes with its minified .class files
        // (the classes are what the size metric measures).
        tmpJar.copyTo(jarFile, overwrite = true)
        classesDir.deleteRecursively()
        copy {
            from(zipTree(tmpJar)) { include("**/*.class") }
            into(classesDir)
        }
        tmpJar.delete()
        val classBytes = classesDir.walkTopDown().filter { it.isFile }.sumOf { it.length() }
        println("Minified in place -> classes %d B (%.2f KB), jar %d B  %s"
            .format(classBytes, classBytes / 1024.0, jarFile.length(), jarFile.name))
    }
}

// Build and run both go through ProGuard, so the jar and the classes that ship/execute are minified.
tasks.named("build") { dependsOn("proguard") }
tasks.named("run") { dependsOn("proguard") }

tasks.register("size") {
    group = "verification"
    description = "Reports total runtime size (minified classes + resources) and the packaged jar size."
    dependsOn("proguard")
    doLast {
        val measured = listOf(
            layout.buildDirectory.dir("classes/java/main").get().asFile,
            layout.buildDirectory.dir("resources/main").get().asFile,
        )
        var totalBytes = 0L
        var fileCount = 0
        measured.filter { it.exists() }.forEach { root ->
            root.walkTopDown().filter { it.isFile }.sortedBy { it.path }.forEach { file ->
                totalBytes += file.length()
                fileCount++
                println("%9d B  %s".format(file.length(), file.relativeTo(root.parentFile)))
            }
        }
        val kilobytes = totalBytes / 1024.0
        println("-".repeat(48))
        println("Files: %d".format(fileCount))
        println("Total: %d B (%.2f KB)".format(totalBytes, kilobytes))

        val jarFile = tasks.named<Jar>("jar").get().archiveFile.get().asFile
        if (jarFile.exists()) {
            println("Jar: %d B (%.2f KB)  %s".format(jarFile.length(), jarFile.length() / 1024.0, jarFile.name))
        }
    }
}
