#!/usr/bin/env bash
# Hill-climbing refinement of inline-allowlist.txt, parallelized. The per-candidate tuner (tune-inline.sh)
# measures each method against the empty baseline and unions the winners, which is blind to interaction
# effects. This warm-starts from the current allowlist and, each round, measures every single add/remove move
# against the REAL pipeline, then applies the one that shrinks the build most, until no single move helps -
# a better local optimum accounting for redundant or synergistic inlines.
#
# The measurements within a round are independent, so they run across N isolated copies of the project (each
# with its own build dir and Gradle daemon - a single dir can't build concurrently because of the project
# lock). Override worker count with PARALLEL=N. Run from the project root: bash tools/refine-inline.sh
set -uo pipefail

N=${PARALLEL:-10}
SRC="$(pwd)"
WORK="/tmp/tune-work"
RES="/tmp/tune-res"
trap 'rm -rf "$WORK" "$RES"' EXIT

elapsed() { printf '%dm%02ds' $((SECONDS / 60)) $((SECONDS % 60)); }
measure() { ( cd "$1" && ./gradlew -q size -Pinline="$2" 2>/dev/null | sed -n 's/^Total: \([0-9]\+\) B.*/\1/p' ); }

mapfile -t candidates < <(./gradlew -q listInlineCandidates 2>/dev/null | grep '#' | sort -u)
M=${#candidates[@]}

declare -A inset
while read -r m; do [[ "$m" == *"#"* ]] && inset["$m"]=1; done < <(grep '#' inline-allowlist.txt)

# CSV of the current set, with one candidate's membership flipped (empty arg = no flip).
csv_with_toggle() {
  local out=() c in
  for c in "${candidates[@]}"; do
    in=""; [[ -n "${inset[$c]:-}" ]] && in=1
    [[ "$c" == "$1" ]] && { [[ -n "$in" ]] && in="" || in=1; }
    [[ -n "$in" ]] && out+=("$c")
  done
  local IFS=,
  echo "${out[*]}"
}

echo "Setting up $N working copies..." >&2
rm -rf "$WORK"; mkdir -p "$WORK"
for i in $(seq 1 "$N"); do
  mkdir -p "$WORK/c$i"
  tar -C "$SRC" --exclude=./build --exclude=./.git --exclude=./.gradle --exclude=./.idea --exclude=./scratch \
      --exclude=./buildSrc/build --exclude=./buildSrc/.gradle -cf - . | tar -C "$WORK/c$i" -xf -
done

SECONDS=0
best=$(measure "$WORK/c1" "$(csv_with_toggle "")")
echo "start: ${best} B ($(grep -c '#' inline-allowlist.txt) methods, $M candidates, $N workers) - $(elapsed)" >&2

round=0
while true; do
  round=$((round + 1))
  rm -rf "$RES"; mkdir -p "$RES"
  for w in $(seq 0 $((N - 1))); do
    (
      for ((idx = w; idx < M; idx += N)); do
        sz=$(measure "$WORK/c$((w + 1))" "$(csv_with_toggle "${candidates[idx]}")")
        echo "${sz:-X}" > "$RES/$idx"
        printf '  round %d: %d/%d passes - %s\n' "$round" "$(find "$RES" -type f | wc -l)" "$M" "$(elapsed)" >&2
      done
    ) &
  done
  wait

  bestMove=""; bestSize=$best
  for ((idx = 0; idx < M; idx++)); do
    sz=$(cat "$RES/$idx" 2>/dev/null)
    [[ -z "$sz" || "$sz" == "X" ]] && continue
    if ((sz < bestSize)); then bestSize=$sz; bestMove="${candidates[idx]}"; fi
  done
  if [[ -z "$bestMove" ]]; then echo "round ${round}: converged at ${best} B - $(elapsed)" >&2; break; fi
  if [[ -n "${inset[$bestMove]:-}" ]]; then unset 'inset[$bestMove]'; act=remove; else inset["$bestMove"]=1; act=add; fi
  best=$bestSize
  echo "round ${round}: ${act} ${bestMove} -> ${best} B - $(elapsed)" >&2
done

{
  echo "// Generated by tools/refine-inline.sh - hill-climbed for interaction effects. Total: ${best} B."
  for c in "${candidates[@]}"; do [[ -n "${inset[$c]:-}" ]] && echo "$c"; done | sort
} > inline-allowlist.txt
echo "wrote $(grep -c '#' inline-allowlist.txt) methods at ${best} B - $(elapsed)" >&2
