@echo off
rem Windows port of tools/refine-inline.sh. Hill-climbs inline-allowlist.txt: each round measures every single
rem add/remove move against the real build and applies the biggest win, until none helps. Runs N project copies in
rem parallel (one Gradle daemon each, since a dir can't build concurrently). Override with `set PARALLEL=N`.
setlocal enabledelayedexpansion
if "%~1"=="__worker" goto worker_entry
pushd "%~dp0.."

set "GRADLEW=gradlew.bat"
if not defined PARALLEL set "PARALLEL=10"
set "N=%PARALLEL%"
set /a Ndec=N-1
set "WORK=%TEMP%\tune-work"
set "RES=%TEMP%\tune-res"

rem --- candidate list (indexed into CAND_0..CAND_<M-1>) ---
echo Listing candidates... 1>&2
set "CANDFILE=%TEMP%\refine-cands-%RANDOM%.txt"
%GRADLEW% -q listInlineCandidates 2>nul | findstr "#" | sort > "%CANDFILE%"
set /a M=0
for /f "usebackq delims=" %%C in ("%CANDFILE%") do (
    set "CAND_!M!=%%C"
    set /a M+=1
)
del "%CANDFILE%" 2>nul
if %M%==0 (
    echo No inline candidates reported - nothing to refine. 1>&2
    popd & endlocal & exit /b 1
)
set /a Mdec=M-1

rem --- seed membership (IN_<idx> defined) from the current allowlist ---
set /a inCount=0
if exist inline-allowlist.txt (
    for /l %%I in (0,1,%Mdec%) do (
        set "IN_%%I="
        findstr /x /c:"!CAND_%%I!" inline-allowlist.txt >nul 2>nul && ( set "IN_%%I=1" & set /a inCount+=1 )
    )
)

rem --- N isolated working copies ---
echo Setting up %N% working copies... 1>&2
if exist "%WORK%" rmdir /s /q "%WORK%"
mkdir "%WORK%"
for /l %%i in (1,1,%N%) do (
    robocopy "%CD%" "%WORK%\c%%i" /E /NFL /NDL /NJH /NJS /NC /NS /NP ^
        /XD "%CD%\build" "%CD%\.git" "%CD%\.gradle" "%CD%\.idea" "%CD%\scratch" "%CD%\buildSrc\build" "%CD%\buildSrc\.gradle" >nul
)

rem --- baseline: the current set, no move applied, measured in the first copy ---
call :build_csv -1 baseCsv
call :measure 1 "!baseCsv!" best
if "!best!"=="" (
    echo Baseline build failed - check that `gradlew size` works. 1>&2
    goto cleanup
)
echo start: !best! B (!inCount! methods, %M% candidates, %N% workers) 1>&2

set /a round=0
:roundloop
set /a round+=1
if exist "%RES%" rmdir /s /q "%RES%"
mkdir "%RES%"

rem Build each toggled -Pinline value up front (cheap); workers only run the builds. <idx>.csv in, <idx> out.
for /l %%I in (0,1,%Mdec%) do (
    call :build_csv %%I tmpcsv
    > "%RES%\%%I.csv" echo(!tmpcsv!
)

for /l %%w in (0,1,%Ndec%) do start "rfw%%w" /b "%ComSpec%" /c call "%~f0" __worker %%w

:waitloop
set /a wdone=0
for /l %%w in (0,1,%Ndec%) do if exist "%RES%\done.%%w" set /a wdone+=1
if %wdone% lss %N% (
    <nul set /p "=." 1>&2
    ping -n 2 127.0.0.1 >nul
    goto waitloop
)
echo. 1>&2
echo   round %round%: %N%/%N% workers done 1>&2

rem --- pick the single move that shrinks the build most (numeric compare via signed diff) ---
set "bestMove="
set "bestMoveIdx=-1"
set "bestSize=!best!"
for /l %%I in (0,1,%Mdec%) do (
    set "sz="
    if exist "%RES%\%%I" set /p sz=<"%RES%\%%I"
    if defined sz if not "!sz!"=="X" (
        set /a d=sz-bestSize
        if !d! lss 0 ( set "bestSize=!sz!" & set "bestMove=!CAND_%%I!" & set "bestMoveIdx=%%I" )
    )
)

if "!bestMove!"=="" (
    echo round %round%: converged at !best! B 1>&2
    goto write
)
if defined IN_!bestMoveIdx! ( set "IN_!bestMoveIdx!=" & set "act=remove" ) else ( set "IN_!bestMoveIdx!=1" & set "act=add" )
set "best=!bestSize!"
echo round %round%: !act! !bestMove! -^> !best! B 1>&2
goto roundloop

:write
> inline-allowlist.txt echo // Generated by tools\refine-inline.bat - hill-climbed for interaction effects. Total: !best! B.
set "MEMFILE=%TEMP%\refine-mem-%RANDOM%.txt"
if exist "%MEMFILE%" del "%MEMFILE%"
set /a finalCount=0
for /l %%I in (0,1,%Mdec%) do if defined IN_%%I ( echo !CAND_%%I!>>"%MEMFILE%" & set /a finalCount+=1 )
if exist "%MEMFILE%" ( sort "%MEMFILE%" >> inline-allowlist.txt & del "%MEMFILE%" )
echo wrote !finalCount! methods at !best! B 1>&2

:cleanup
if exist "%WORK%" rmdir /s /q "%WORK%" 2>nul
if exist "%RES%" rmdir /s /q "%RES%" 2>nul
popd
endlocal
exit /b 0

rem build_csv: %1 = candidate index to flip (-1 = none), %2 = out var. Emits the -Pinline CSV with the toggle applied.
:build_csv
setlocal enabledelayedexpansion
set "tog=%~1"
set "s="
for /l %%I in (0,1,%Mdec%) do (
    set "mem="
    if defined IN_%%I set "mem=1"
    if %%I==!tog! ( if defined mem (set "mem=") else (set "mem=1") )
    if defined mem ( if defined s (set "s=!s!,!CAND_%%I!") else (set "s=!CAND_%%I!") )
)
endlocal & set "%~2=%s%"
exit /b

rem measure: %1 = copy number, %2 = quoted -Pinline value, %3 = out var. Builds in that copy, parses the Total: size.
:measure
setlocal
set "out=%TEMP%\refine-size-%RANDOM%.txt"
pushd "%WORK%\c%~1"
call gradlew.bat -q size -Pinline=%~2 > "%out%" 2>nul
popd
set "value="
for /f "usebackq tokens=2" %%T in (`findstr /b /c:"Total:" "%out%"`) do set "value=%%T"
del "%out%" 2>nul
endlocal & set "%~3=%value%"
exit /b

rem worker_entry (__worker <w>): own process per round, inherits N/M/WORK/RES. Measures indices w, w+N, ... in copy
rem c<w+1>, writes each size to RES\<idx> then RES\done.<w>. Guard: idx>=M iff idx-M is non-negative.
:worker_entry
set "w=%~2"
set /a wnum=w+1
set /a idx=w
:wnext
set /a over=idx-%M%
if !over! geq 0 goto wflag
set "csv="
set /p csv=<"%RES%\!idx!.csv"
set "wout=%RES%\!idx!.out"
pushd "%WORK%\c!wnum!"
call gradlew.bat -q size -Pinline=!csv! > "!wout!" 2>nul
popd
set "value=X"
for /f "usebackq tokens=2" %%T in (`findstr /b /c:"Total:" "!wout!"`) do set "value=%%T"
> "%RES%\!idx!" echo !value!
del "!wout!" 2>nul
set /a idx+=%N%
goto wnext
:wflag
> "%RES%\done.%w%" echo done
exit /b
