#!/usr/bin/env bash
# Regenerates inline-allowlist.txt for the build-time method inliner (see buildSrc).
#
# A static gate inside the build cannot predict ProGuard's optimizer, so each single-call candidate is
# measured against the REAL pipeline: build with only that method inlined, run ProGuard, read the total size.
# A candidate is kept iff inlining it alone shrinks the build. Slow (one full build per candidate) but exact;
# rerun it whenever the game source changes. Run from the project root: bash tools/tune-inline.sh
set -uo pipefail

gradle() { ./gradlew -q "$@" 2>/dev/null; }
total()  { gradle size "$@" | sed -n 's/^Total: \([0-9]\+\) B.*/\1/p'; }

echo "Measuring baseline (no inlining)..." >&2
base=$(total -Pinline=)
echo "  baseline = ${base} B" >&2

mapfile -t candidates < <(gradle listInlineCandidates | grep '#')
echo "Measuring ${#candidates[@]} candidates..." >&2

winners=()
for candidate in "${candidates[@]}"; do
  measured=$(total -Pinline="$candidate")
  if [[ -z "$measured" ]]; then
    printf '  %-34s MEASURE FAILED (skipped)\n' "$candidate" >&2
    continue
  fi
  delta=$((measured - base))
  if (( delta < 0 )); then
    winners+=("$candidate")
    printf '  %-34s %+d  KEEP\n' "$candidate" "$delta" >&2
  else
    printf '  %-34s %+d\n' "$candidate" "$delta" >&2
  fi
done

{
  echo "// Generated by tools/tune-inline.sh - single-call methods whose inlining shrinks the post-ProGuard build."
  echo "// Regenerate after changing the game source. Measured baseline: ${base} B."
  printf '%s\n' "${winners[@]}" | sort
} > inline-allowlist.txt

echo "Wrote ${#winners[@]} winners to inline-allowlist.txt" >&2
