@echo off
rem Regenerates inline-allowlist.txt for the build-time method inliner (see buildSrc) - Windows port of
rem tools/tune-inline.sh. A static gate inside the build cannot predict the optimizer, so each single-call
rem candidate is measured against the REAL pipeline: build with only that method inlined and read the total
rem size. A candidate is kept iff inlining it alone shrinks the build. One full build per candidate, so it is
rem slow but exact; rerun it whenever the game source changes. Just run it: tools\tune-inline.bat
rem (pushd %~dp0.. below makes it work from any location - the project can live anywhere.)
setlocal enabledelayedexpansion
pushd "%~dp0.."

set "GRADLEW=gradlew.bat"
set "CANDIDATES=%TEMP%\inline-cands-%RANDOM%.txt"
set "WINNERS=%TEMP%\inline-winners-%RANDOM%.txt"
if exist "%WINNERS%" del "%WINNERS%"

echo Measuring baseline (no inlining)...
call :measure "-Pinline=" base
echo   baseline = !base! B

echo Listing candidates...
%GRADLEW% -q listInlineCandidates 2>nul | findstr "#" > "%CANDIDATES%"

echo Measuring candidates...
for /f "usebackq delims=" %%C in ("%CANDIDATES%") do (
    set "candidate=%%C"
    call :measure "-Pinline=!candidate!" measured
    if "!measured!"=="" (
        echo   !candidate!  MEASURE FAILED ^(skipped^)
    ) else (
        set /a delta=measured-base
        if !measured! lss !base! (
            echo !candidate!>>"%WINNERS%"
            echo   !candidate!  !delta!  KEEP
        ) else (
            echo   !candidate!  +!delta!
        )
    )
)
del "%CANDIDATES%" 2>nul

> inline-allowlist.txt echo // Generated by tools\tune-inline.bat - single-call methods whose inlining shrinks the post-ProGuard build.
>> inline-allowlist.txt echo // Regenerate after changing the game source. Measured baseline: !base! B.
if exist "%WINNERS%" (
    sort "%WINNERS%" >> inline-allowlist.txt
    del "%WINNERS%"
)

echo Done. Wrote inline-allowlist.txt
popd
endlocal
exit /b 0

:measure
rem %1 = quoted -Pinline argument, %2 = name of the variable to receive the total size (empty on failure).
rem Gradle is run with `call` (so control returns) into a temp file, then parsed - a `#` in the inline arg
rem cannot go inside a for /f command, where it would truncate the line.
setlocal
set "out=%TEMP%\inline-size-%RANDOM%.txt"
call %GRADLEW% -q size %~1 > "%out%" 2>nul
set "value="
for /f "usebackq tokens=2" %%T in (`findstr /b /c:"Total:" "%out%"`) do set "value=%%T"
del "%out%" 2>nul
endlocal & set "%~2=%value%"
exit /b
